### ISSUE TITLE
Can't publish 0.0.10

### ISSUE THREAD

**Issue by vjeux** [jlongster/prettier-atom#33]
@robwise turns out because you published 0.0.10 but didn't update the dependency to 0.0.10, we are now stuck as we can't publish the 0.0.10 again. I also tried publishing 0.0.10b or 0.0.10-real but atom doesn't seem to like it.

The plan is to do another smaller release either today or tomorrow and we'll bump everything to 0.0.11.

(Note: this is the first time I ever publish something to apm so there may be a way!)

**Comment by robwise** [comment]
@vjeux You mean you are trying to mirror Prettier's semver? I don't think that's a good idea. If we have a game-stopping bug on the plugin we shouldn't have to wait for Prettier to get bumped before we can release it just so the semvers can match. 

I published v10 to get a plugin-specific enhancement released, that's why I didn't bump the dependency. If we want to bump the dependency, we should just release that as version 11 IMO.
