### ISSUE TITLE
Disable fix on save from linter-eslint?

### ISSUE THREAD

**Issue by kentcdodds** [jlongster/prettier-atom#63]
Is it possible to disable linter-eslint's fix unsaved from this plugin when people choose fix on safe in this plugin?

**Comment by robwise** [comment]
Yes, I think so. One of the things I've seen other packages do is show a warning dialog if it detects both options are enabled at once. That might be a more preferable way to do it because otherwise, you are going to get weird edge cases. For example, if we disable ESlint's autofix, then the user disables prettier-atom, should we turn the ESlint autofix back on? How do we remember whether they had it on or off?

**Comment by kentcdodds** [comment]
Good point. Probably a warning would be good

**Comment by robwise** [comment]
Fixed in https://github.com/jlongster/prettier-atom/pull/64
